"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Lang = "pt" | "zh";

const dict = {
  pt: {
    // ── Nav / Header ──────────────────────────────────────────────────────
    nav_products: "Produtos",
    nav_my_orders: "Meus pedidos",
    nav_my_profile: "Meu perfil",
    nav_admin_panel: "Painel admin",
    nav_panel: "Painel",
    nav_login: "Entrar",
    nav_logout: "Sair",

    // ── Footer ────────────────────────────────────────────────────────────
    footer_tagline: "Produtos importados com cuidado, entregues com qualidade.",
    footer_store: "Loja",
    footer_products: "Produtos",
    footer_featured: "Destaques",

    // ── LogoutConfirm ─────────────────────────────────────────────────────
    logout_title: "Sair da conta?",
    logout_body: "Você precisará entrar novamente para acessar sua conta.",
    logout_cancel: "Cancelar",
    logout_confirm: "Sair",

    // ── LoginModal ────────────────────────────────────────────────────────
    login_title: "Entrar",
    login_subtitle: "Use seu e-mail ou username",
    login_label_id: "E-mail ou username",
    login_label_pw: "Senha",
    login_submitting: "Entrando...",
    login_submit: "Entrar",
    login_no_account: "Não tem conta?",
    login_create: "Criar conta",
    login_error_default: "Erro ao fazer login",

    // ── Hero ──────────────────────────────────────────────────────────────
    hero_badge: "Produtos importados",
    hero_title: "Qualidade direto\npara você.",
    hero_subtitle: "Encontre o que precisa, faça seu pedido e acompanhe cada etapa. Simples assim.",
    hero_cta_products: "Ver produtos",
    hero_cta_register: "Criar conta",

    // ── Home ──────────────────────────────────────────────────────────────
    home_featured: "Destaques",
    home_see_all: "Ver todos →",
    home_empty: "Em breve novos produtos por aqui.",
    home_catalog: "Ver catálogo",

    // ── CTA ───────────────────────────────────────────────────────────────
    cta_title: "Pronto para comprar?",
    cta_subtitle: "Cadastre-se e faça seu primeiro pedido.",
    cta_button: "Criar conta grátis",

    // ── ProductCard ───────────────────────────────────────────────────────
    card_no_image: "sem imagem",

    // ── Produtos page ─────────────────────────────────────────────────────
    products_title_all: "Todos os produtos",
    products_title_featured: "Destaques",
    products_count_one: "produto encontrado",
    products_count_many: "produtos encontrados",
    products_search_placeholder: "Buscar produto...",
    products_search_btn: "Buscar",
    products_filter: "Filtrar",
    products_all: "Todos",
    products_featured_filter: "★ Destaques",
    products_categories: "Categorias",
    products_clear_filter: "Limpar filtro",
    products_none_title: "Nenhum produto encontrado",
    products_none_try: "Tente outros filtros ou ",
    products_none_see_all: "ver todos os produtos",
    products_none_soon: "Em breve novos produtos por aqui.",

    // ── Product detail ────────────────────────────────────────────────────
    product_home: "Início",
    product_products: "Produtos",
    product_no_image: "sem imagem",
    product_featured_badge: "★ Destaque",
    product_payment_note: "Pagamento confirmado manualmente · Envio após confirmação",
    product_description: "Descrição",

    // ── AddToCart ─────────────────────────────────────────────────────────
    addtocart_out_of_stock: "esgotado",
    addtocart_select_variation: "Selecione uma variação antes de adicionar ao carrinho",
    addtocart_added: "Adicionado ao carrinho",
    addtocart_add: "Adicionar ao carrinho",

    // ── CartDrawer ────────────────────────────────────────────────────────
    cart_title: "Carrinho",
    cart_empty: "Seu carrinho está vazio",
    cart_keep_shopping: "Continuar comprando",
    cart_no_image: "sem imagem",
    cart_total: "Total",
    cart_checkout: "Finalizar compra",
    cart_login_to_checkout: "Entrar para finalizar",

    // ── Checkout ──────────────────────────────────────────────────────────
    checkout_title: "Finalizar compra",
    checkout_subtitle: "Confirme o endereço de entrega",
    checkout_address_section: "Endereço de entrega",
    checkout_name: "Nome do destinatário *",
    checkout_phone: "Telefone",
    checkout_zip: "CEP *",
    checkout_number: "Número *",
    checkout_street: "Rua / Logradouro *",
    checkout_complement: "Complemento",
    checkout_neighborhood: "Bairro *",
    checkout_city: "Cidade *",
    checkout_state: "UF *",
    checkout_notes: "Observações (opcional)",
    checkout_notes_placeholder: "Instruções de entrega, referências...",
    checkout_submitting: "Processando...",
    checkout_submit: "Confirmar pedido",
    checkout_summary: "Resumo do pedido",
    checkout_qty: "Qtd:",
    checkout_total: "Total",
    checkout_empty: "Seu carrinho está vazio.",
    checkout_see_products: "Ver produtos",
    checkout_error_default: "Erro ao criar pedido. Tente novamente.",
    checkout_success_title: "Pedido #{id} realizado!",
    checkout_success_body: "Agora realize o pagamento via PIX para confirmarmos seu pedido.",
    checkout_see_orders: "Ver meus pedidos",
    checkout_continue: "Continuar comprando",

    // ── PIX Info ──────────────────────────────────────────────────────────
    pix_title: "Pague via PIX",
    pix_subtitle: "Transferência instantânea · confirmaremos em até 24h",
    pix_key_label: "Chave PIX",
    pix_amount_label: "Valor a pagar",
    pix_exact: "Transferir exatamente este valor",
    pix_copy: "Copiar",
    pix_copied: "Copiado!",
    pix_note: "Após o pagamento, aguarde a confirmação. Você acompanha o status em",
    pix_note_link: "Meus pedidos",

    // ── Meus Pedidos ──────────────────────────────────────────────────────
    orders_title: "Meus pedidos",
    orders_subtitle: "Acompanhe o status das suas compras",
    orders_none: "Você ainda não fez nenhum pedido.",
    orders_see_products: "Ver produtos",
    orders_order: "Pedido #",
    orders_items_one: "item",
    orders_items_many: "itens",
    orders_tracking_available: "Rastreio disponível",
    orders_modal_items: "Itens",
    orders_modal_total: "Total",
    orders_modal_tracking: "Código de rastreio",
    orders_modal_notes: "Observações",
    orders_modal_close: "Fechar",
    orders_modal_cancel: "Cancelar pedido",
    orders_cancel_error_default: "Não foi possível cancelar o pedido.",

    // ── Order Status Labels ───────────────────────────────────────────────
    status_pending: "Aguardando confirmação",
    status_confirmed: "Confirmado",
    status_paid: "Pagamento recebido",
    status_processing: "Em processamento",
    status_shipped: "Enviado",
    status_delivered: "Entregue",
    status_cancelled: "Cancelado",

    // ── Perfil ────────────────────────────────────────────────────────────
    profile_title: "Meu perfil",
    profile_subtitle: "Gerencie suas informações pessoais",
    profile_account_data: "Dados da conta",
    profile_username: "Username",
    profile_email: "E-mail",
    profile_type: "Tipo",
    profile_type_pf: "Pessoa Física",
    profile_type_pj: "Pessoa Jurídica",
    profile_member_since: "Membro desde",
    profile_personal_info: "Informações pessoais",
    profile_full_name: "Nome completo",
    profile_phone: "Telefone",
    profile_company: "Nome da empresa",
    profile_saving: "Salvando...",
    profile_save: "Salvar alterações",
    profile_saved_ok: "Perfil atualizado com sucesso.",
    profile_save_err: "Erro ao atualizar perfil.",
    profile_change_pw: "Alterar senha",
    profile_current_pw: "Senha atual",
    profile_new_pw: "Nova senha",
    profile_confirm_pw: "Confirmar nova senha",
    profile_confirm_pw_placeholder: "Repita a nova senha",
    profile_pw_changing: "Alterando...",
    profile_pw_change: "Alterar senha",
    profile_pw_ok: "Senha alterada com sucesso.",
    profile_pw_err: "Erro ao alterar senha.",
    profile_pw_mismatch: "A nova senha e a confirmação não coincidem.",
    profile_pw_too_short: "A nova senha deve ter no mínimo 6 caracteres.",

    // ── Cadastro ──────────────────────────────────────────────────────────
    register_title: "Criar conta",
    register_has_account: "Já tem conta?",
    register_back_login: "Voltar e entrar",
    register_pf: "Pessoa Física",
    register_pj: "Pessoa Jurídica",
    register_full_name: "Nome completo *",
    register_username: "Username *",
    register_email: "E-mail *",
    register_phone: "Telefone",
    register_company: "Nome da empresa *",
    register_cnpj: "CNPJ",
    register_cpf: "CPF",
    register_password: "Senha *",
    register_confirm_pw: "Confirmar senha *",
    register_pw_placeholder: "Mínimo 6 caracteres",
    register_submitting: "Criando conta...",
    register_submit: "Criar conta",
    register_success: "Conta criada com sucesso!",
    register_redirecting: "Redirecionando...",
    register_err_name: "Nome completo é obrigatório.",
    register_err_username: "Username é obrigatório.",
    register_err_email: "E-mail é obrigatório.",
    register_err_pw_short: "Senha deve ter no mínimo 6 caracteres.",
    register_err_pw_mismatch: "As senhas não coincidem.",
    register_err_cpf: "CPF inválido.",
    register_err_company: "Nome da empresa é obrigatório para PJ.",
    register_err_cnpj: "CNPJ inválido.",
    register_err_default: "Erro ao criar conta.",
    register_cpf_invalid: "CPF inválido",
    register_cpf_valid: "CPF válido",
    register_cnpj_invalid: "CNPJ inválido",
    register_cnpj_valid: "CNPJ válido",
    register_pw_mismatch_hint: "Senhas não coincidem",
    register_pw_match_hint: "Senhas coincidem",
    register_razao_social: "Razão social",
    register_name_placeholder: "Seu nome",
    register_username_placeholder: "seunome123",

    // ── Admin Layout ──────────────────────────────────────────────────────
    admin_panel_subtitle: "Painel admin",
    admin_nav_dashboard: "Dashboard",
    admin_nav_orders: "Pedidos",
    admin_nav_products: "Produtos",
    admin_nav_categories: "Categorias",
    admin_nav_suppliers: "Fornecedores",
    admin_nav_users: "Usuários",
    admin_logout: "Sair",

    // ── Admin Dashboard ───────────────────────────────────────────────────
    admin_dash_title: "Dashboard",
    admin_dash_subtitle: "Visão geral do negócio",
    admin_dash_customers: "Clientes",
    admin_dash_products: "Produtos ativos",
    admin_dash_total_orders: "Total de pedidos",
    admin_dash_pending: "Aguardando confirmação",
    admin_dash_awaiting_pay: "Aguardando pagamento",
    admin_dash_to_review: "Comprovantes a revisar",
    admin_dash_revenue: "Receita bruta",
    admin_dash_profit: "Lucro estimado",

    // ── Admin Pedidos ─────────────────────────────────────────────────────
    admin_orders_title: "Pedidos",
    admin_orders_subtitle: "Gerencie os pedidos dos clientes",
    admin_orders_none: "Nenhum pedido encontrado.",
    admin_orders_all: "Todos",
    admin_orders_item: "item",
    admin_orders_items: "itens",
    admin_orders_modal_items: "Itens do pedido",
    admin_orders_customer_total: "Total do cliente",
    admin_orders_customer_notes: "Obs. do cliente",
    admin_orders_manage: "Gerenciar pedido",
    admin_orders_status: "Status",
    admin_orders_supplier: "Fornecedor",
    admin_orders_no_supplier: "Nenhum",
    admin_orders_tracking: "Código de rastreio",
    admin_orders_tracking_placeholder: "Código dos Correios ou transportadora",
    admin_orders_internal_notes: "Notas internas",
    admin_orders_internal_placeholder: "Anotações internas (não visível ao cliente)",
    admin_orders_cancel: "Cancelar pedido",
    admin_orders_close: "Fechar",
    admin_orders_saving: "Salvando...",
    admin_orders_save: "Salvar alterações",
    admin_orders_err_update: "Erro ao atualizar pedido.",
    admin_orders_err_cancel: "Erro ao cancelar.",
    admin_orders_status_pending: "Aguardando",
    admin_orders_status_confirmed: "Confirmado",
    admin_orders_status_paid: "Pago",
    admin_orders_status_purchasing: "Comprando",
    admin_orders_status_shipped: "Enviado",
    admin_orders_status_delivered: "Entregue",
    admin_orders_status_cancelled: "Cancelado",

    // ── Admin Usuários ────────────────────────────────────────────────────
    admin_users_title: "Usuários",
    admin_users_subtitle: "Clientes e administradores cadastrados",
    admin_users_search: "Buscar por nome, e-mail ou username...",
    admin_users_all_roles: "Todos os perfis",
    admin_users_role_buyer: "Clientes",
    admin_users_role_admin: "Admins",
    admin_users_role_superadmin: "Superadmin",
    admin_users_all_status: "Todos os status",
    admin_users_active: "Ativos",
    admin_users_inactive: "Inativos",
    admin_users_count_one: "usuário",
    admin_users_count_many: "usuários",
    admin_users_none: "Nenhum usuário encontrado.",
    admin_users_type_pf: "Pessoa Física",
    admin_users_type_pj: "Pessoa Jurídica",
    admin_users_label_email: "E-mail",
    admin_users_label_type: "Tipo",
    admin_users_label_company: "Empresa",
    admin_users_label_phone: "Telefone",
    admin_users_label_role: "Perfil",
    admin_users_label_verified: "Verificado",
    admin_users_label_status: "Status",
    admin_users_label_since: "Cadastro",
    admin_users_yes: "Sim",
    admin_users_no: "Não",
    admin_users_status_active: "Ativo",
    admin_users_status_inactive: "Inativo",
    admin_users_deactivate: "Desativar conta",
    admin_users_reactivate: "Reativar conta",
    admin_users_close: "Fechar",
    admin_users_role_buyer_label: "Cliente",
    admin_users_role_admin_label: "Admin",

    // ── Admin Fornecedores ────────────────────────────────────────────────
    admin_sup_title: "Fornecedores",
    admin_sup_subtitle: "Empresas e contatos de onde você compra",
    admin_sup_show_inactive: "Ver inativos",
    admin_sup_new: "Novo fornecedor",
    admin_sup_none: "Nenhum fornecedor cadastrado.",
    admin_sup_create_first: "Criar o primeiro",
    admin_sup_inactive_badge: "inativo",
    admin_sup_edit_title: "Editar fornecedor",
    admin_sup_new_title: "Novo fornecedor",
    admin_sup_field_name: "Nome *",
    admin_sup_field_contact: "Contato",
    admin_sup_field_whatsapp: "WhatsApp",
    admin_sup_field_email: "E-mail",
    admin_sup_field_website: "Website",
    admin_sup_field_country: "País",
    admin_sup_field_notes: "Observações",
    admin_sup_field_notes_ph: "Notas internas sobre este fornecedor...",
    admin_sup_cancel: "Cancelar",
    admin_sup_saving: "Salvando...",
    admin_sup_save: "Salvar",
    admin_sup_create: "Criar",
    admin_sup_open_website: "Abrir website",
    admin_sup_deactivate: "Desativar",
    admin_sup_activate: "Ativar",
    admin_sup_edit: "Editar",

    // ── Admin Categorias ──────────────────────────────────────────────────
    admin_cat_title: "Categorias",
    admin_cat_subtitle: "Gerencie as categorias de produtos",
    admin_cat_new: "Nova categoria",
    admin_cat_none: "Nenhuma categoria cadastrada.",
    admin_cat_new_title: "Nova categoria",
    admin_cat_edit_title: "Editar categoria",
    admin_cat_field_name: "Nome *",
    admin_cat_field_slug: "Slug",
    admin_cat_field_desc: "Descrição",
    admin_cat_field_icon: "Ícone URL",
    admin_cat_field_parent: "Categoria pai",
    admin_cat_no_parent: "Sem pai (raiz)",
    admin_cat_field_active: "Ativo",
    admin_cat_cancel: "Cancelar",
    admin_cat_saving: "Salvando...",
    admin_cat_save: "Salvar",
    admin_cat_create: "Criar",
    admin_cat_add_sub: "Adicionar subcategoria",
    admin_cat_deactivate: "Desativar",
    admin_cat_activate: "Ativar",
    admin_cat_edit: "Editar",

    // ── Admin Produtos ────────────────────────────────────────────────────
    admin_prod_title: "Produtos",
    admin_prod_subtitle: "Gerencie o catálogo de produtos",
    admin_prod_new: "Novo produto",
    admin_prod_none: "Nenhum produto cadastrado.",
    admin_prod_search: "Buscar produto...",
    admin_prod_featured_badge: "Destaque",
    admin_prod_inactive_badge: "Inativo",
    admin_prod_edit: "Editar",
    admin_prod_delete: "Excluir definitivamente",
    admin_prod_delete_confirm: "Excluir o produto \"{name}\" PERMANENTEMENTE? As imagens no S3 também serão apagadas. Esta ação não pode ser desfeita.",
    admin_prod_tab_basic: "Dados básicos",
    admin_prod_tab_suppliers: "Fornecedores",
    admin_prod_tab_variations: "Variações",
    admin_prod_field_name: "Nome *",
    admin_prod_field_slug: "Slug",
    admin_prod_field_short_desc: "Descrição curta",
    admin_prod_field_desc: "Descrição completa",
    admin_prod_field_price: "Preço de venda (R$) *",
    admin_prod_field_category: "Categoria",
    admin_prod_no_category: "Sem categoria",
    admin_prod_field_featured: "Produto em destaque",
    admin_prod_field_active: "Produto ativo",
    admin_prod_cancel: "Cancelar",
    admin_prod_saving: "Salvando...",
    admin_prod_save: "Salvar",
    admin_prod_create: "Criar produto",
    admin_prod_new_title: "Novo produto",
    admin_prod_edit_title: "Editar produto",
    admin_prod_sup_pref: "Fornecedor preferido",
    admin_prod_sup_cost: "Custo (R$)",
    admin_prod_sup_url: "URL do produto no fornecedor",
    admin_prod_sup_notes: "Notas",
    admin_prod_sup_add: "Vincular fornecedor",
    admin_prod_sup_none: "Nenhum fornecedor vinculado.",
    admin_prod_var_name: "Tipo",
    admin_prod_var_value: "Valor",
    admin_prod_var_price_mod: "Modificador preço (R$)",
    admin_prod_var_stock: "Estoque",
    admin_prod_var_active: "Ativo",
    admin_prod_var_add: "Adicionar variação",
    admin_prod_var_none: "Nenhuma variação.",
    admin_prod_tab_images: "Imagens",
    admin_prod_img_cover: "Capa",
    admin_prod_img_set_cover: "Definir como capa",
    admin_prod_img_delete: "Excluir imagem",
    admin_prod_img_upload_hint: "Clique para enviar uma imagem",
    admin_prod_img_uploading: "Enviando...",
    admin_prod_img_none: "Nenhuma imagem. Envie a primeira acima.",
    admin_prod_img_cover_section: "Imagem de capa",
    admin_prod_img_cover_hint: "Imagem principal exibida na listagem e no topo do produto.",
    admin_prod_img_cover_upload: "Enviar capa",
    admin_prod_img_gallery_section: "Galeria",
    admin_prod_img_gallery_hint: "Imagens adicionais exibidas como miniaturas na página do produto.",
    // ── Cadastro em massa ─────────────────────────────────────────────────
    admin_bulk_new: "Adicionar em massa",
    admin_bulk_title: "Cadastro de produtos em massa",
    admin_bulk_subtitle: "Adicione vários produtos de uma vez. As imagens vão direto para o S3 e tudo é enviado numa única chamada.",
    admin_bulk_back: "Voltar para produtos",
    admin_bulk_add_product: "Adicionar produto",
    admin_bulk_product: "Produto",
    admin_bulk_remove: "Remover",
    admin_bulk_name: "Nome *",
    admin_bulk_price: "Preço de venda (R$) *",
    admin_bulk_category: "Categoria",
    admin_bulk_short_desc: "Descrição curta",
    admin_bulk_desc: "Descrição completa",
    admin_bulk_supplier: "Fornecedor",
    admin_bulk_supplier_none: "Nenhum",
    admin_bulk_cost: "Custo (R$)",
    admin_bulk_supplier_sku: "SKU do fornecedor",
    admin_bulk_featured: "Destaque",
    admin_bulk_images: "Imagens",
    admin_bulk_pick_folder: "Escolher pasta",
    admin_bulk_pick_files: "Escolher imagens",
    admin_bulk_clear_images: "Limpar",
    admin_bulk_cover_note: "A primeira imagem (ordem alfabética) será a capa.",
    admin_bulk_images_count: "imagem(ns) selecionada(s)",
    admin_bulk_cover_label: "capa",
    admin_bulk_no_products: "Nenhum produto adicionado. Clique em \"Adicionar produto\".",
    admin_bulk_submit: "Enviar todos",
    admin_bulk_submitting: "Enviando...",
    admin_bulk_uploading_images: "Enviando imagens",
    admin_bulk_creating: "Criando produtos...",
    admin_bulk_result_title: "Resultado do envio",
    admin_bulk_created: "criados",
    admin_bulk_failed: "com erro",
    admin_bulk_clear_ok: "Limpar e novo lote",
    admin_bulk_err_no_products: "Adicione pelo menos um produto.",
    admin_bulk_err_missing: "Preencha nome e preço de todos os produtos.",
    admin_bulk_err_generic: "Ocorreu um erro no envio.",
    admin_bulk_validating: "Validando...",
  },

  zh: {
    // ── Nav / Header ──────────────────────────────────────────────────────
    nav_products: "商品",
    nav_my_orders: "我的订单",
    nav_my_profile: "我的资料",
    nav_admin_panel: "管理面板",
    nav_panel: "管理",
    nav_login: "登录",
    nav_logout: "退出",

    // ── Footer ────────────────────────────────────────────────────────────
    footer_tagline: "精心采购的进口商品，品质保证配送。",
    footer_store: "商店",
    footer_products: "商品",
    footer_featured: "精选",

    // ── LogoutConfirm ─────────────────────────────────────────────────────
    logout_title: "确认退出账号？",
    logout_body: "退出后需要重新登录才能访问账号。",
    logout_cancel: "取消",
    logout_confirm: "退出",

    // ── LoginModal ────────────────────────────────────────────────────────
    login_title: "登录",
    login_subtitle: "使用邮箱或用户名登录",
    login_label_id: "邮箱或用户名",
    login_label_pw: "密码",
    login_submitting: "登录中...",
    login_submit: "登录",
    login_no_account: "还没有账号？",
    login_create: "立即注册",
    login_error_default: "登录失败，请重试",

    // ── Hero ──────────────────────────────────────────────────────────────
    hero_badge: "进口商品",
    hero_title: "品质直达，\n为您而来。",
    hero_subtitle: "找到您需要的商品，轻松下单，全程追踪。就是这么简单。",
    hero_cta_products: "浏览商品",
    hero_cta_register: "注册账号",

    // ── Home ──────────────────────────────────────────────────────────────
    home_featured: "精选推荐",
    home_see_all: "查看全部 →",
    home_empty: "更多商品即将上线。",
    home_catalog: "查看目录",

    // ── CTA ───────────────────────────────────────────────────────────────
    cta_title: "准备好购买了吗？",
    cta_subtitle: "注册账号并下您的第一单。",
    cta_button: "免费注册",

    // ── ProductCard ───────────────────────────────────────────────────────
    card_no_image: "暂无图片",

    // ── Produtos page ─────────────────────────────────────────────────────
    products_title_all: "全部商品",
    products_title_featured: "精选推荐",
    products_count_one: "件商品",
    products_count_many: "件商品",
    products_search_placeholder: "搜索商品...",
    products_search_btn: "搜索",
    products_filter: "筛选",
    products_all: "全部",
    products_featured_filter: "★ 精选",
    products_categories: "分类",
    products_clear_filter: "清除筛选",
    products_none_title: "未找到商品",
    products_none_try: "请尝试其他筛选条件，或 ",
    products_none_see_all: "查看全部商品",
    products_none_soon: "更多商品即将上线。",

    // ── Product detail ────────────────────────────────────────────────────
    product_home: "首页",
    product_products: "商品",
    product_no_image: "暂无图片",
    product_featured_badge: "★ 精选",
    product_payment_note: "人工确认付款 · 确认后发货",
    product_description: "商品详情",

    // ── AddToCart ─────────────────────────────────────────────────────────
    addtocart_out_of_stock: "缺货",
    addtocart_select_variation: "请先选择规格再加入购物车",
    addtocart_added: "已加入购物车",
    addtocart_add: "加入购物车",

    // ── CartDrawer ────────────────────────────────────────────────────────
    cart_title: "购物车",
    cart_empty: "购物车为空",
    cart_keep_shopping: "继续购物",
    cart_no_image: "暂无图片",
    cart_total: "合计",
    cart_checkout: "去结算",
    cart_login_to_checkout: "登录后结算",

    // ── Checkout ──────────────────────────────────────────────────────────
    checkout_title: "结算",
    checkout_subtitle: "确认收货地址",
    checkout_address_section: "收货地址",
    checkout_name: "收件人姓名 *",
    checkout_phone: "联系电话",
    checkout_zip: "邮政编码 (CEP) *",
    checkout_number: "门牌号 *",
    checkout_street: "街道地址 *",
    checkout_complement: "补充地址",
    checkout_neighborhood: "区/街区 *",
    checkout_city: "城市 *",
    checkout_state: "州 *",
    checkout_notes: "备注（可选）",
    checkout_notes_placeholder: "配送说明、参考信息...",
    checkout_submitting: "处理中...",
    checkout_submit: "确认下单",
    checkout_summary: "订单摘要",
    checkout_qty: "数量:",
    checkout_total: "合计",
    checkout_empty: "购物车为空。",
    checkout_see_products: "查看商品",
    checkout_error_default: "下单失败，请重试。",
    checkout_success_title: "订单 #{id} 已提交！",
    checkout_success_body: "请通过 PIX 完成付款，我们将确认您的订单。",
    checkout_see_orders: "查看我的订单",
    checkout_continue: "继续购物",

    // ── PIX Info ──────────────────────────────────────────────────────────
    pix_title: "通过 PIX 付款",
    pix_subtitle: "即时转账 · 24小时内确认",
    pix_key_label: "PIX 密钥",
    pix_amount_label: "应付金额",
    pix_exact: "请精确转账此金额",
    pix_copy: "复制",
    pix_copied: "已复制！",
    pix_note: "付款后请等待确认，您可在",
    pix_note_link: "我的订单",

    // ── Meus Pedidos ──────────────────────────────────────────────────────
    orders_title: "我的订单",
    orders_subtitle: "追踪您的购物状态",
    orders_none: "您还没有任何订单。",
    orders_see_products: "浏览商品",
    orders_order: "订单 #",
    orders_items_one: "件商品",
    orders_items_many: "件商品",
    orders_tracking_available: "可追踪物流",
    orders_modal_items: "商品明细",
    orders_modal_total: "合计",
    orders_modal_tracking: "物流追踪号",
    orders_modal_notes: "备注",
    orders_modal_close: "关闭",
    orders_modal_cancel: "取消订单",
    orders_cancel_error_default: "无法取消订单。",

    // ── Order Status Labels ───────────────────────────────────────────────
    status_pending: "等待确认",
    status_confirmed: "已确认",
    status_paid: "已收款",
    status_processing: "处理中",
    status_shipped: "已发货",
    status_delivered: "已送达",
    status_cancelled: "已取消",

    // ── Perfil ────────────────────────────────────────────────────────────
    profile_title: "我的资料",
    profile_subtitle: "管理您的个人信息",
    profile_account_data: "账号信息",
    profile_username: "用户名",
    profile_email: "邮箱",
    profile_type: "类型",
    profile_type_pf: "个人",
    profile_type_pj: "企业",
    profile_member_since: "注册时间",
    profile_personal_info: "个人信息",
    profile_full_name: "全名",
    profile_phone: "联系电话",
    profile_company: "公司名称",
    profile_saving: "保存中...",
    profile_save: "保存修改",
    profile_saved_ok: "资料更新成功。",
    profile_save_err: "资料更新失败。",
    profile_change_pw: "修改密码",
    profile_current_pw: "当前密码",
    profile_new_pw: "新密码",
    profile_confirm_pw: "确认新密码",
    profile_confirm_pw_placeholder: "再次输入新密码",
    profile_pw_changing: "修改中...",
    profile_pw_change: "修改密码",
    profile_pw_ok: "密码修改成功。",
    profile_pw_err: "密码修改失败。",
    profile_pw_mismatch: "两次输入的密码不一致。",
    profile_pw_too_short: "新密码至少需要6个字符。",

    // ── Cadastro ──────────────────────────────────────────────────────────
    register_title: "注册账号",
    register_has_account: "已有账号？",
    register_back_login: "返回登录",
    register_pf: "个人",
    register_pj: "企业",
    register_full_name: "全名 *",
    register_username: "用户名 *",
    register_email: "邮箱 *",
    register_phone: "联系电话",
    register_company: "公司名称 *",
    register_cnpj: "CNPJ（企业税号）",
    register_cpf: "CPF（个人税号）",
    register_password: "密码 *",
    register_confirm_pw: "确认密码 *",
    register_pw_placeholder: "至少6个字符",
    register_submitting: "注册中...",
    register_submit: "注册",
    register_success: "账号创建成功！",
    register_redirecting: "跳转中...",
    register_err_name: "请填写全名。",
    register_err_username: "请填写用户名。",
    register_err_email: "请填写邮箱。",
    register_err_pw_short: "密码至少需要6个字符。",
    register_err_pw_mismatch: "两次密码不一致。",
    register_err_cpf: "CPF 无效。",
    register_err_company: "企业注册请填写公司名称。",
    register_err_cnpj: "CNPJ 无效。",
    register_err_default: "注册失败，请重试。",
    register_cpf_invalid: "CPF 无效",
    register_cpf_valid: "CPF 有效",
    register_cnpj_invalid: "CNPJ 无效",
    register_cnpj_valid: "CNPJ 有效",
    register_pw_mismatch_hint: "密码不一致",
    register_pw_match_hint: "密码一致",
    register_razao_social: "公司全称",
    register_name_placeholder: "您的姓名",
    register_username_placeholder: "yourname123",

    // ── Admin Layout ──────────────────────────────────────────────────────
    admin_panel_subtitle: "管理面板",
    admin_nav_dashboard: "控制台",
    admin_nav_orders: "订单",
    admin_nav_products: "商品",
    admin_nav_categories: "分类",
    admin_nav_suppliers: "供应商",
    admin_nav_users: "用户",
    admin_logout: "退出",

    // ── Admin Dashboard ───────────────────────────────────────────────────
    admin_dash_title: "控制台",
    admin_dash_subtitle: "业务概览",
    admin_dash_customers: "客户",
    admin_dash_products: "在售商品",
    admin_dash_total_orders: "总订单数",
    admin_dash_pending: "待确认订单",
    admin_dash_awaiting_pay: "待付款",
    admin_dash_to_review: "待审核付款",
    admin_dash_revenue: "总收入",
    admin_dash_profit: "预估利润",

    // ── Admin Pedidos ─────────────────────────────────────────────────────
    admin_orders_title: "订单",
    admin_orders_subtitle: "管理客户订单",
    admin_orders_none: "暂无订单。",
    admin_orders_all: "全部",
    admin_orders_item: "件商品",
    admin_orders_items: "件商品",
    admin_orders_modal_items: "订单商品",
    admin_orders_customer_total: "客户应付",
    admin_orders_customer_notes: "客户备注",
    admin_orders_manage: "管理订单",
    admin_orders_status: "状态",
    admin_orders_supplier: "供应商",
    admin_orders_no_supplier: "无",
    admin_orders_tracking: "物流追踪号",
    admin_orders_tracking_placeholder: "快递或物流单号",
    admin_orders_internal_notes: "内部备注",
    admin_orders_internal_placeholder: "内部备注（客户不可见）",
    admin_orders_cancel: "取消订单",
    admin_orders_close: "关闭",
    admin_orders_saving: "保存中...",
    admin_orders_save: "保存修改",
    admin_orders_err_update: "更新订单失败。",
    admin_orders_err_cancel: "取消失败。",
    admin_orders_status_pending: "待确认",
    admin_orders_status_confirmed: "已确认",
    admin_orders_status_paid: "已付款",
    admin_orders_status_purchasing: "采购中",
    admin_orders_status_shipped: "已发货",
    admin_orders_status_delivered: "已送达",
    admin_orders_status_cancelled: "已取消",

    // ── Admin Usuários ────────────────────────────────────────────────────
    admin_users_title: "用户",
    admin_users_subtitle: "已注册客户和管理员",
    admin_users_search: "按姓名、邮箱或用户名搜索...",
    admin_users_all_roles: "所有角色",
    admin_users_role_buyer: "客户",
    admin_users_role_admin: "管理员",
    admin_users_role_superadmin: "超级管理员",
    admin_users_all_status: "所有状态",
    admin_users_active: "活跃",
    admin_users_inactive: "已停用",
    admin_users_count_one: "个用户",
    admin_users_count_many: "个用户",
    admin_users_none: "未找到用户。",
    admin_users_type_pf: "个人",
    admin_users_type_pj: "企业",
    admin_users_label_email: "邮箱",
    admin_users_label_type: "类型",
    admin_users_label_company: "公司",
    admin_users_label_phone: "电话",
    admin_users_label_role: "角色",
    admin_users_label_verified: "已验证",
    admin_users_label_status: "状态",
    admin_users_label_since: "注册时间",
    admin_users_yes: "是",
    admin_users_no: "否",
    admin_users_status_active: "活跃",
    admin_users_status_inactive: "已停用",
    admin_users_deactivate: "停用账号",
    admin_users_reactivate: "重新激活",
    admin_users_close: "关闭",
    admin_users_role_buyer_label: "客户",
    admin_users_role_admin_label: "管理员",

    // ── Admin Fornecedores ────────────────────────────────────────────────
    admin_sup_title: "供应商",
    admin_sup_subtitle: "您的采购来源企业和联系方式",
    admin_sup_show_inactive: "显示已停用",
    admin_sup_new: "新增供应商",
    admin_sup_none: "暂无供应商。",
    admin_sup_create_first: "创建第一个",
    admin_sup_inactive_badge: "已停用",
    admin_sup_edit_title: "编辑供应商",
    admin_sup_new_title: "新增供应商",
    admin_sup_field_name: "名称 *",
    admin_sup_field_contact: "联系人",
    admin_sup_field_whatsapp: "WhatsApp",
    admin_sup_field_email: "邮箱",
    admin_sup_field_website: "网站",
    admin_sup_field_country: "国家",
    admin_sup_field_notes: "备注",
    admin_sup_field_notes_ph: "关于此供应商的内部备注...",
    admin_sup_cancel: "取消",
    admin_sup_saving: "保存中...",
    admin_sup_save: "保存",
    admin_sup_create: "创建",
    admin_sup_open_website: "访问网站",
    admin_sup_deactivate: "停用",
    admin_sup_activate: "启用",
    admin_sup_edit: "编辑",

    // ── Admin Categorias ──────────────────────────────────────────────────
    admin_cat_title: "分类",
    admin_cat_subtitle: "管理商品分类",
    admin_cat_new: "新增分类",
    admin_cat_none: "暂无分类。",
    admin_cat_new_title: "新增分类",
    admin_cat_edit_title: "编辑分类",
    admin_cat_field_name: "名称 *",
    admin_cat_field_slug: "Slug（URL标识）",
    admin_cat_field_desc: "描述",
    admin_cat_field_icon: "图标链接",
    admin_cat_field_parent: "父分类",
    admin_cat_no_parent: "无（顶级分类）",
    admin_cat_field_active: "启用",
    admin_cat_cancel: "取消",
    admin_cat_saving: "保存中...",
    admin_cat_save: "保存",
    admin_cat_create: "创建",
    admin_cat_add_sub: "添加子分类",
    admin_cat_deactivate: "停用",
    admin_cat_activate: "启用",
    admin_cat_edit: "编辑",

    // ── Admin Produtos ────────────────────────────────────────────────────
    admin_prod_title: "商品",
    admin_prod_subtitle: "管理商品目录",
    admin_prod_new: "新增商品",
    admin_prod_none: "暂无商品。",
    admin_prod_search: "搜索商品...",
    admin_prod_featured_badge: "精选",
    admin_prod_inactive_badge: "已下架",
    admin_prod_edit: "编辑",
    admin_prod_delete: "永久删除",
    admin_prod_delete_confirm: "确定要永久删除商品“{name}”吗？S3 中的图片也将被删除。此操作无法撤销。",
    admin_prod_tab_basic: "基本信息",
    admin_prod_tab_suppliers: "供应商",
    admin_prod_tab_variations: "规格",
    admin_prod_field_name: "名称 *",
    admin_prod_field_slug: "Slug",
    admin_prod_field_short_desc: "简介",
    admin_prod_field_desc: "详细描述",
    admin_prod_field_price: "售价 (R$) *",
    admin_prod_field_category: "分类",
    admin_prod_no_category: "无分类",
    admin_prod_field_featured: "设为精选",
    admin_prod_field_active: "上架商品",
    admin_prod_cancel: "取消",
    admin_prod_saving: "保存中...",
    admin_prod_save: "保存",
    admin_prod_create: "创建商品",
    admin_prod_new_title: "新增商品",
    admin_prod_edit_title: "编辑商品",
    admin_prod_sup_pref: "首选供应商",
    admin_prod_sup_cost: "成本 (R$)",
    admin_prod_sup_url: "供应商商品链接",
    admin_prod_sup_notes: "备注",
    admin_prod_sup_add: "关联供应商",
    admin_prod_sup_none: "暂无关联供应商。",
    admin_prod_var_name: "规格名",
    admin_prod_var_value: "规格值",
    admin_prod_var_price_mod: "价格调整 (R$)",
    admin_prod_var_stock: "库存",
    admin_prod_var_active: "启用",
    admin_prod_var_add: "添加规格",
    admin_prod_var_none: "暂无规格。",
    admin_prod_tab_images: "图片",
    admin_prod_img_cover: "封面",
    admin_prod_img_set_cover: "设为封面",
    admin_prod_img_delete: "删除图片",
    admin_prod_img_upload_hint: "点击上传图片",
    admin_prod_img_uploading: "上传中...",
    admin_prod_img_none: "暂无图片，请在上方上传。",
    admin_prod_img_cover_section: "封面图片",
    admin_prod_img_cover_hint: "在列表和商品页顶部显示的主图。",
    admin_prod_img_cover_upload: "上传封面",
    admin_prod_img_gallery_section: "图库",
    admin_prod_img_gallery_hint: "在商品页以缩略图形式显示的附加图片。",
    // ── 批量录入 ──────────────────────────────────────────────────────────
    admin_bulk_new: "批量添加",
    admin_bulk_title: "批量录入商品",
    admin_bulk_subtitle: "一次添加多个商品。图片直接上传至 S3，所有数据通过一次请求提交。",
    admin_bulk_back: "返回商品列表",
    admin_bulk_add_product: "添加商品",
    admin_bulk_product: "商品",
    admin_bulk_remove: "移除",
    admin_bulk_name: "名称 *",
    admin_bulk_price: "售价（R$）*",
    admin_bulk_category: "分类",
    admin_bulk_short_desc: "简短描述",
    admin_bulk_desc: "完整描述",
    admin_bulk_supplier: "供应商",
    admin_bulk_supplier_none: "无",
    admin_bulk_cost: "成本（R$）",
    admin_bulk_supplier_sku: "供应商 SKU",
    admin_bulk_featured: "推荐",
    admin_bulk_images: "图片",
    admin_bulk_pick_folder: "选择文件夹",
    admin_bulk_pick_files: "选择图片",
    admin_bulk_clear_images: "清空",
    admin_bulk_cover_note: "第一张图片（按字母顺序）将作为封面。",
    admin_bulk_images_count: "已选择图片",
    admin_bulk_cover_label: "封面",
    admin_bulk_no_products: "尚未添加商品。请点击“添加商品”。",
    admin_bulk_submit: "全部提交",
    admin_bulk_submitting: "提交中...",
    admin_bulk_uploading_images: "正在上传图片",
    admin_bulk_creating: "正在创建商品...",
    admin_bulk_result_title: "提交结果",
    admin_bulk_created: "成功",
    admin_bulk_failed: "失败",
    admin_bulk_clear_ok: "清空并开始新批次",
    admin_bulk_err_no_products: "请至少添加一个商品。",
    admin_bulk_err_missing: "请填写所有商品的名称和价格。",
    admin_bulk_err_generic: "提交时发生错误。",
    admin_bulk_validating: "验证中...",
  },
} as const;

export type Translations = typeof dict.pt;

type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "pt",
  setLang: () => {},
  t: dict.pt,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("pt");

  useEffect(() => {
    const stored = localStorage.getItem("bb_lang") as Lang | null;
    if (stored === "pt" || stored === "zh") setLangState(stored);
  }, []);

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem("bb_lang", l);
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: dict[lang] as Translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
